name: build kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Set up MemKernel as a module (M-OUT) with specified name
      run: |
        curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s M xyor

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: X15
      with:
        arch: arm64
        compiler: gcc/12
        defconfig: gki_defconfig
        image: Image.gz-dtb

    - name: Upload Kernel and Module
      uses: actions/upload-artifact@v4
      with:
        name: moduleandkernel
        path: |
          ${{ steps.build.outputs.outfile }}
          ./out/drivers/memkernel/memkernel.ko        
